version: "3.9"
services:
  api:
    build: .
    container_name: livewell_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: livewell_redis
    ports:
      - "6379:6379"
